### PR TITLE
Fix usage of deprecated getSystemWidnowInsets

### PR DESCRIPTION
**Pull request by jann-0**

### CODE REVIEW

**Comment by Zanthed** [comment]
I think we'd actually want to replace insets all together and use a proper layout like so here (not finished): https://github.com/smdyv/PdfViewer/commit/267ff843e6876390d6391f8ae68a6fda104b742e

**Comment by jann-0** [comment]
Makes sense.

**Comment by Zanthed** [comment]
https://github.com/GrapheneOS/PdfViewer/pull/154

**Comment by jann-0** [comment]
Thanks for that follow up!

**Pull request closed without merging**
